### ISSUE TITLE
Plugin Crashes Site On Local DesktopServer Install

### ISSUE THREAD

**Issue by kengmick** [nickcernis/ssi-custom-icons#1]
Activating this plugin, without any modifications, crashes my local DesktopServer dev site.  I'm using DesktopServer Premium v3.8.3 which runs on XAMPP Lite.  

( ! ) Fatal error: Cannot redeclare class Config in C:\xampplite\php\PEAR\Config.php on line 44
--

I'm able to activate this plugin on a SiteGround hosted staging site without issues, with the same Genesis Sample child theme/Beaver Builder website.

**Comment by nickcernis** [comment]
Thanks for the report, Ken.

If you'd like to test a potential fix for this, you're welcome to download this version: https://github.com/nickcernis/ssi-custom-icons/archive/fix-xampp.zip

I'll update master if that works for you.

**Comment by kengmick** [comment]
Hi Nick, The fix works great.  The revised plugin activated fine, and is operational with DesktopServer.  Thank you for this helpful plugin and the super prompt support.

**Comment by kengmick** [comment]
by the way, I am utilizing this plugin to add Yelp and a map marker for GoogleMaps.

**Comment by kengmick** [comment]
next step, update master

**Comment by nickcernis** [comment]
Thanks for testing, Ken, and nice idea about the map marker! Master updated for 0.1.1.
